In [1]:
from pathlib import Path
import pandas as pd

In [2]:
data_dir = Path()
csv_file_path = data_dir / "creditcard.csv"

In [3]:
credit_card_raw_data = pd.read_csv(csv_file_path)

credit_card_data = credit_card_raw_data.copy()

In [7]:
credit_card_data.head()

#Time -> represents the seconds elapsed between first transaction in the dataset
# V1 - V28 -> principal components obtained with PCA, the original features are not provided due to confidentiality issues
# Amount -> transaction amount
# Class -> target variable, 1 for fraud and 0 for non-fraud transactions

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [12]:
# data summary function

def data_summary(data_frame, max_examples=3):
    """Returns summary table of every column in data frame. Returns also selected number of examples for each column. 
    Default number of examples is 3."""
    rows = []

    for col in data_frame.columns:
        d = data_frame[col]
        record = {
            "column": col,
            "data_type": d.dtype,
            "not empty": d.notna().sum(),
            "missings": d.isna().sum(),
            "missings_%": d.isna().sum() / len(d) * 100,
            "unique": d.nunique(),
            "unique_%": d.nunique() / len(d) * 100,
            "examples": ", ".join(map(str, d.dropna().unique()[: max_examples])),
        }
        if pd.api.types.is_numeric_dtype(d):
            record["mean"] = d.mean()
            record["median"] = d.median()
            record["std"] = d.std()
            record["min"] = d.min()
            record["max"] = d.max()

        rows.append(record)
    return pd.DataFrame(rows).set_index("column")

data_summary(credit_card_data)

,data_type,not empty,missings,missings_%,unique,unique_%,examples,mean,median,std,min,max
column,,,,,,,,,,,,
Time,float64,284807,0,0.0,124592,43.746116,"0.0, 1.0, 2.0",9.481386e+04,84692.000000,47488.145955,0.000000,172792.000000
V1,float64,284807,0,0.0,275663,96.789405,"-1.3598071336738, 1.19185711131486, -1.3583540...",1.175161e-15,0.018109,1.958696,-56.407510,2.454930
V2,float64,284807,0,0.0,275663,96.789405,"-0.0727811733098497, 0.26615071205963, -1.3401...",3.384974e-16,0.065486,1.651309,-72.715728,22.057729
V3,float64,284807,0,0.0,275663,96.789405,"2.53634673796914, 0.16648011335321, 1.77320934...",-1.379537e-15,0.179846,1.516255,-48.325589,9.382558
V4,float64,284807,0,0.0,275663,96.789405,"1.37815522427443, 0.448154078460911, 0.3797795...",2.094852e-15,-0.019847,1.415869,-5.683171,16.875344
V5,float64,284807,0,0.0,275663,96.789405,"-0.338320769942518, 0.0600176492822243, -0.503...",1.021879e-15,-0.054336,1.380247,-113.743307,34.801666
V6,float64,284807,0,0.0,275663,96.789405,"0.462387777762292, -0.0823608088155687, 1.8004...",1.494498e-15,-0.274187,1.332271,-26.160506,73.301626
V7,float64,284807,0,0.0,275663,96.789405,"0.239598554061257, -0.0788029833323113, 0.7914...",-5.620335e-16,0.040103,1.237094,-43.557242,120.589494
V8,float64,284807,0,0.0,275663,96.789405,"0.0986979012610507, 0.0851016549148104, 0.2476...",1.149614e-16,0.022358,1.194353,-73.216718,20.007208
V9,float64,284807,0,0.0,275663,96.789405,"0.363786969611213, -0.255425128109186, -1.5146...",-2.414189e-15,-0.051429,1.098632,-13.434066,15.594995
V10,float64,284807,0,0.0,275663,96.789405,"0.0907941719789316, -0.166974414004614, 0.2076...",2.238554e-15,-0.092917,1.088850,-24.588262,23.745136
V11,float64,284807,0,0.0,275663,96.789405,"-0.551599533260813, 1.61272666105479, 0.624501...",1.724421e-15,-0.032757,1.020713,-4.797473,12.018913
V12,float64,284807,0,0.0,275663,96.789405,"-0.617800855762348, 1.06523531137287, 0.066083...",-1.245415e-15,0.140033,0.999201,-18.683715,7.848392
V13,float64,284807,0,0.0,275663,96.789405,"-0.991389847235408, 0.48909501589608, 0.717292...",8.238900e-16,-0.013568,0.995274,-5.791881,7.126883
V14,float64,284807,0,0.0,275663,96.789405,"-0.311169353699879, -0.143772296441519, -0.165...",1.213481e-15,0.050601,0.958596,-19.214325,10.526766
V15,float64,284807,0,0.0,275663,96.789405,"1.46817697209427, 0.635558093258208, 2.3458649...",4.866699e-15,0.048072,0.915316,-4.498945,8.877742
V16,float64,284807,0,0.0,275663,96.789405,"-0.470400525259478, 0.463917041022171, -2.8900...",1.436219e-15,0.066413,0.876253,-14.129855,17.315112
V17,float64,284807,0,0.0,275663,96.789405,"0.207971241929242, -0.114804663102346, 1.10996...",-3.768179e-16,-0.065676,0.849337,-25.162799,9.253526
V18,float64,284807,0,0.0,275663,96.789405,"0.0257905801985591, -0.183361270123994, -0.121...",9.707851e-16,-0.003636,0.838176,-9.498746,5.041069
V19,float64,284807,0,0.0,275663,96.789405,"0.403992960255733, -0.145783041325259, -2.2618...",1.036249e-15,0.003735,0.814041,-7.213527,5.591971
V20,float64,284807,0,0.0,275663,96.789405,"0.251412098239705, -0.0690831352230203, 0.5249...",6.418678e-16,-0.062481,0.770925,-54.497720,39.420904
V21,float64,284807,0,0.0,275663,96.789405,"-0.018306777944153, -0.225775248033138, 0.2479...",1.628620e-16,-0.029450,0.734524,-34.830382,27.202839
V22,float64,284807,0,0.0,275663,96.789405,"0.277837575558899, -0.638671952771851, 0.77167...",-3.576577e-16,0.006782,0.725702,-10.933144,10.503090
V23,float64,284807,0,0.0,275663,96.789405,"-0.110473910188767, 0.101288021253234, 0.90941...",2.618565e-16,-0.011193,0.624460,-44.807735,22.528412
V24,float64,284807,0,0.0,275663,96.789405,"0.0669280749146731, -0.339846475529127, -0.689...",4.473914e-15,0.040976,0.605647,-2.836627,4.584549
V25,float64,284807,0,0.0,275663,96.789405,"0.128539358273528, 0.167170404418143, -0.32764...",5.109395e-16,0.016594,0.521278,-10.295397,7.519589
V26,float64,284807,0,0.0,275663,96.789405,"-0.189114843888824, 0.125894532368176, -0.1390...",1.686100e-15,-0.052139,0.482227,-2.604551,3.517346
V27,float64,284807,0,0.0,275663,96.789405,"0.133558376740387, -0.0089830991432281, -0.055...",-3.661401e-16,0.001342,0.403632,-22.565679,31.612198
V28,float64,284807,0,0.0,275663,96.789405,"-0.0210530534538215, 0.0147241691924927, -0.05...",-1.227452e-16,0.011244,0.330083,-15.430084,33.847808
Amount,float64,284807,0,0.0,32767,11.504984,"149.62, 2.69, 378.66",8.834962e+01,22.000000,250.120109,0.000000,25691.160000
Class,int64,284807,0,0.0,2,0.000702,"0, 1",1.727486e-03,0.000000,0.041527,0.000000,1.000000

In [8]:
#1. Data shape
print(f"Data shape: {credit_card_data.shape}")

#2. Data types in columns
data_types_check = (
    credit_card_data
    .columns.to_series() #change to series to use groupby, column names are index and values
    .groupby(credit_card_data.dtypes)
    .apply(list)
)

display(data_types_check)

Data shape: (284807, 31)

int64                                                [Class]
float64    [Time, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10...
dtype: object

In [6]:
display(credit_card_data.dtypes)

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object